// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SampleEmployeeManagementSystem.DataAccess.Data;

#nullable disable

namespace SampleEmployeeManagementSystem.DataAccess.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241022142634_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("SampleEmployeeManagementSystem.DataAccess.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Departement")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = -36,
                            DateOfBirth = new DateTime(1988, 5, 25, 20, 54, 3, 203, DateTimeKind.Local).AddTicks(8109),
                            Departement = "Engineering",
                            FullName = "Alan Kreiger",
                            PhoneNumber = "(784) 603-5805"
                        },
                        new
                        {
                            Id = 2,
                            Age = -46,
                            DateOfBirth = new DateTime(1978, 12, 13, 7, 59, 23, 889, DateTimeKind.Local).AddTicks(3028),
                            Departement = "Training and development",
                            FullName = "Peggy Rohan",
                            PhoneNumber = "1-281-800-2316 x67983"
                        },
                        new
                        {
                            Id = 3,
                            Age = -53,
                            DateOfBirth = new DateTime(1971, 4, 28, 14, 17, 6, 941, DateTimeKind.Local).AddTicks(3130),
                            Departement = "Finance",
                            FullName = "Carole West",
                            PhoneNumber = "703.988.0652 x00290"
                        },
                        new
                        {
                            Id = 4,
                            Age = -67,
                            DateOfBirth = new DateTime(1957, 8, 26, 6, 24, 45, 483, DateTimeKind.Local).AddTicks(2487),
                            Departement = "Sales",
                            FullName = "Jacob Conroy",
                            PhoneNumber = "1-751-703-1331 x801"
                        },
                        new
                        {
                            Id = 5,
                            Age = -23,
                            DateOfBirth = new DateTime(2001, 6, 5, 12, 45, 8, 8, DateTimeKind.Local).AddTicks(2521),
                            Departement = "Sales",
                            FullName = "Irving Leffler",
                            PhoneNumber = "(967) 246-5663"
                        },
                        new
                        {
                            Id = 6,
                            Age = -69,
                            DateOfBirth = new DateTime(1955, 1, 25, 12, 33, 42, 56, DateTimeKind.Local).AddTicks(4397),
                            Departement = "Information Technology (IT)",
                            FullName = "Edith Marks",
                            PhoneNumber = "793-257-9183 x05447"
                        },
                        new
                        {
                            Id = 7,
                            Age = -52,
                            DateOfBirth = new DateTime(1972, 9, 22, 0, 45, 51, 621, DateTimeKind.Local).AddTicks(5454),
                            Departement = "Training and development",
                            FullName = "Heather Sanford",
                            PhoneNumber = "985-517-9124"
                        },
                        new
                        {
                            Id = 8,
                            Age = -52,
                            DateOfBirth = new DateTime(1972, 4, 27, 20, 16, 58, 251, DateTimeKind.Local).AddTicks(4515),
                            Departement = "Training and development",
                            FullName = "Melvin Rutherford",
                            PhoneNumber = "1-237-937-3326 x00717"
                        },
                        new
                        {
                            Id = 9,
                            Age = -25,
                            DateOfBirth = new DateTime(1999, 12, 23, 0, 43, 16, 746, DateTimeKind.Local).AddTicks(1201),
                            Departement = "Training and development",
                            FullName = "Karla Koepp",
                            PhoneNumber = "943-209-1906 x8358"
                        },
                        new
                        {
                            Id = 10,
                            Age = -40,
                            DateOfBirth = new DateTime(1984, 1, 27, 20, 49, 18, 51, DateTimeKind.Local).AddTicks(8801),
                            Departement = "Administration",
                            FullName = "Bridget Goyette",
                            PhoneNumber = "914.506.6387"
                        },
                        new
                        {
                            Id = 11,
                            Age = -46,
                            DateOfBirth = new DateTime(1978, 7, 28, 16, 36, 27, 850, DateTimeKind.Local).AddTicks(9740),
                            Departement = "Information Technology (IT)",
                            FullName = "Denise Jones",
                            PhoneNumber = "1-444-404-8768"
                        },
                        new
                        {
                            Id = 12,
                            Age = -54,
                            DateOfBirth = new DateTime(1970, 3, 15, 12, 20, 40, 857, DateTimeKind.Local).AddTicks(3781),
                            Departement = "Engineering",
                            FullName = "Rodney Heller",
                            PhoneNumber = "679-865-2608"
                        },
                        new
                        {
                            Id = 13,
                            Age = -28,
                            DateOfBirth = new DateTime(1996, 4, 13, 14, 52, 17, 128, DateTimeKind.Local).AddTicks(5085),
                            Departement = "Engineering",
                            FullName = "Nora Legros",
                            PhoneNumber = "1-678-672-8408"
                        },
                        new
                        {
                            Id = 14,
                            Age = -36,
                            DateOfBirth = new DateTime(1988, 1, 11, 5, 55, 5, 824, DateTimeKind.Local).AddTicks(3459),
                            Departement = "Training and development",
                            FullName = "Julia Bogisich",
                            PhoneNumber = "206.436.1099 x58168"
                        },
                        new
                        {
                            Id = 15,
                            Age = -61,
                            DateOfBirth = new DateTime(1963, 12, 29, 16, 30, 6, 290, DateTimeKind.Local).AddTicks(7960),
                            Departement = "Training and development",
                            FullName = "Sandy Wintheiser",
                            PhoneNumber = "1-334-615-7143"
                        },
                        new
                        {
                            Id = 16,
                            Age = -61,
                            DateOfBirth = new DateTime(1963, 11, 7, 18, 36, 32, 615, DateTimeKind.Local).AddTicks(9790),
                            Departement = "Customer support",
                            FullName = "Stella O'Kon",
                            PhoneNumber = "1-452-280-5863 x1400"
                        },
                        new
                        {
                            Id = 17,
                            Age = -53,
                            DateOfBirth = new DateTime(1971, 1, 17, 1, 25, 29, 759, DateTimeKind.Local).AddTicks(7119),
                            Departement = "Training and development",
                            FullName = "Ora Douglas",
                            PhoneNumber = "(797) 500-8448 x22311"
                        },
                        new
                        {
                            Id = 18,
                            Age = -51,
                            DateOfBirth = new DateTime(1973, 6, 27, 13, 6, 0, 577, DateTimeKind.Local).AddTicks(6824),
                            Departement = "Administration",
                            FullName = "Kent Rippin",
                            PhoneNumber = "1-537-579-2052 x6038"
                        },
                        new
                        {
                            Id = 19,
                            Age = -49,
                            DateOfBirth = new DateTime(1975, 12, 27, 7, 41, 23, 653, DateTimeKind.Local).AddTicks(3921),
                            Departement = "Customer support",
                            FullName = "Wesley Gutkowski",
                            PhoneNumber = "280-310-5496"
                        },
                        new
                        {
                            Id = 20,
                            Age = -29,
                            DateOfBirth = new DateTime(1995, 9, 2, 13, 40, 38, 185, DateTimeKind.Local).AddTicks(6433),
                            Departement = "Customer support",
                            FullName = "Henrietta Barton",
                            PhoneNumber = "897-584-4832 x1124"
                        },
                        new
                        {
                            Id = 21,
                            Age = -52,
                            DateOfBirth = new DateTime(1972, 6, 16, 1, 40, 34, 787, DateTimeKind.Local).AddTicks(4250),
                            Departement = "Finance",
                            FullName = "Darryl Miller",
                            PhoneNumber = "507-263-2233"
                        },
                        new
                        {
                            Id = 22,
                            Age = -45,
                            DateOfBirth = new DateTime(1979, 12, 6, 7, 43, 43, 330, DateTimeKind.Local).AddTicks(7788),
                            Departement = "Business Development",
                            FullName = "Joshua Fahey",
                            PhoneNumber = "234-211-1499 x5409"
                        },
                        new
                        {
                            Id = 23,
                            Age = -24,
                            DateOfBirth = new DateTime(2000, 12, 24, 6, 20, 51, 950, DateTimeKind.Local).AddTicks(7276),
                            Departement = "Quality Assurance (QA)",
                            FullName = "Leticia Lockman",
                            PhoneNumber = "1-528-792-5372"
                        },
                        new
                        {
                            Id = 24,
                            Age = -69,
                            DateOfBirth = new DateTime(1955, 7, 26, 17, 51, 28, 292, DateTimeKind.Local).AddTicks(8291),
                            Departement = "Finance",
                            FullName = "Bruce Raynor",
                            PhoneNumber = "942-606-1929"
                        },
                        new
                        {
                            Id = 25,
                            Age = -51,
                            DateOfBirth = new DateTime(1973, 11, 5, 15, 50, 32, 992, DateTimeKind.Local).AddTicks(4748),
                            Departement = "Information Technology (IT)",
                            FullName = "Miguel Dare",
                            PhoneNumber = "(512) 986-9988 x5569"
                        },
                        new
                        {
                            Id = 26,
                            Age = -24,
                            DateOfBirth = new DateTime(2000, 4, 3, 17, 45, 57, 838, DateTimeKind.Local).AddTicks(6767),
                            Departement = "Business Development",
                            FullName = "Sonya Purdy",
                            PhoneNumber = "841.345.0998"
                        },
                        new
                        {
                            Id = 27,
                            Age = -65,
                            DateOfBirth = new DateTime(1959, 11, 15, 11, 6, 41, 950, DateTimeKind.Local).AddTicks(2563),
                            Departement = "Administration",
                            FullName = "Alexander Kuphal",
                            PhoneNumber = "207-494-3235"
                        },
                        new
                        {
                            Id = 28,
                            Age = -39,
                            DateOfBirth = new DateTime(1985, 8, 26, 0, 27, 16, 728, DateTimeKind.Local).AddTicks(8429),
                            Departement = "Information Technology (IT)",
                            FullName = "Janice Barrows",
                            PhoneNumber = "653-279-1648 x546"
                        },
                        new
                        {
                            Id = 29,
                            Age = -23,
                            DateOfBirth = new DateTime(2001, 4, 24, 21, 10, 8, 307, DateTimeKind.Local).AddTicks(8778),
                            Departement = "Sales",
                            FullName = "Blake Kertzmann",
                            PhoneNumber = "1-257-550-6806"
                        },
                        new
                        {
                            Id = 30,
                            Age = -28,
                            DateOfBirth = new DateTime(1996, 2, 20, 10, 8, 48, 192, DateTimeKind.Local).AddTicks(8024),
                            Departement = "Finance",
                            FullName = "Josephine Price",
                            PhoneNumber = "302.813.9296 x5054"
                        },
                        new
                        {
                            Id = 31,
                            Age = -29,
                            DateOfBirth = new DateTime(1995, 2, 2, 17, 35, 1, 697, DateTimeKind.Local).AddTicks(4965),
                            Departement = "Administration",
                            FullName = "Sheryl Boyer",
                            PhoneNumber = "787.507.9076 x1112"
                        },
                        new
                        {
                            Id = 32,
                            Age = -33,
                            DateOfBirth = new DateTime(1991, 4, 16, 19, 40, 31, 83, DateTimeKind.Local).AddTicks(5544),
                            Departement = "Sales",
                            FullName = "Mack Effertz",
                            PhoneNumber = "1-590-429-4881 x47620"
                        },
                        new
                        {
                            Id = 33,
                            Age = -26,
                            DateOfBirth = new DateTime(1998, 5, 17, 23, 55, 42, 730, DateTimeKind.Local).AddTicks(9702),
                            Departement = "Information Technology (IT)",
                            FullName = "Mae Breitenberg",
                            PhoneNumber = "1-867-642-0420 x50626"
                        },
                        new
                        {
                            Id = 34,
                            Age = -37,
                            DateOfBirth = new DateTime(1987, 9, 1, 0, 23, 12, 650, DateTimeKind.Local).AddTicks(3571),
                            Departement = "Sales",
                            FullName = "Kurt Kozey",
                            PhoneNumber = "1-433-905-5081 x0978"
                        },
                        new
                        {
                            Id = 35,
                            Age = -27,
                            DateOfBirth = new DateTime(1997, 6, 15, 3, 21, 24, 423, DateTimeKind.Local).AddTicks(5636),
                            Departement = "Training and development",
                            FullName = "Traci Lebsack",
                            PhoneNumber = "318-207-9001 x40362"
                        },
                        new
                        {
                            Id = 36,
                            Age = -53,
                            DateOfBirth = new DateTime(1971, 6, 12, 1, 43, 21, 368, DateTimeKind.Local).AddTicks(6119),
                            Departement = "Training and development",
                            FullName = "Kristine Cartwright",
                            PhoneNumber = "408.735.4088 x6887"
                        },
                        new
                        {
                            Id = 37,
                            Age = -37,
                            DateOfBirth = new DateTime(1987, 6, 21, 21, 36, 6, 345, DateTimeKind.Local).AddTicks(891),
                            Departement = "Administration",
                            FullName = "Wilma Herzog",
                            PhoneNumber = "1-261-352-3565 x740"
                        },
                        new
                        {
                            Id = 38,
                            Age = -26,
                            DateOfBirth = new DateTime(1998, 11, 18, 15, 16, 0, 307, DateTimeKind.Local).AddTicks(7450),
                            Departement = "Customer support",
                            FullName = "Maxine Little",
                            PhoneNumber = "1-633-437-2441 x24163"
                        },
                        new
                        {
                            Id = 39,
                            Age = -27,
                            DateOfBirth = new DateTime(1997, 5, 6, 4, 3, 3, 184, DateTimeKind.Local).AddTicks(1430),
                            Departement = "Information Technology (IT)",
                            FullName = "Lonnie Heaney",
                            PhoneNumber = "470.932.1982 x5160"
                        },
                        new
                        {
                            Id = 40,
                            Age = -36,
                            DateOfBirth = new DateTime(1988, 1, 9, 5, 16, 46, 85, DateTimeKind.Local).AddTicks(8282),
                            Departement = "Finance",
                            FullName = "Kirk Durgan",
                            PhoneNumber = "(988) 791-3269 x77052"
                        },
                        new
                        {
                            Id = 41,
                            Age = -47,
                            DateOfBirth = new DateTime(1977, 8, 11, 20, 4, 37, 860, DateTimeKind.Local).AddTicks(3831),
                            Departement = "Engineering",
                            FullName = "Lawrence Spinka",
                            PhoneNumber = "721-229-3147 x83955"
                        },
                        new
                        {
                            Id = 42,
                            Age = -68,
                            DateOfBirth = new DateTime(1956, 8, 15, 5, 40, 10, 18, DateTimeKind.Local).AddTicks(8323),
                            Departement = "Sales",
                            FullName = "Clay Renner",
                            PhoneNumber = "(974) 496-1472"
                        },
                        new
                        {
                            Id = 43,
                            Age = -60,
                            DateOfBirth = new DateTime(1964, 8, 26, 22, 28, 13, 897, DateTimeKind.Local).AddTicks(5538),
                            Departement = "Sales",
                            FullName = "Marcos Balistreri",
                            PhoneNumber = "(358) 777-1648"
                        },
                        new
                        {
                            Id = 44,
                            Age = -64,
                            DateOfBirth = new DateTime(1960, 4, 11, 0, 38, 55, 820, DateTimeKind.Local).AddTicks(6573),
                            Departement = "Sales",
                            FullName = "Emilio Pouros",
                            PhoneNumber = "253.389.5981 x6265"
                        },
                        new
                        {
                            Id = 45,
                            Age = -22,
                            DateOfBirth = new DateTime(2002, 7, 11, 17, 7, 11, 726, DateTimeKind.Local).AddTicks(1635),
                            Departement = "Engineering",
                            FullName = "Tammy Hintz",
                            PhoneNumber = "1-673-274-4650 x0950"
                        },
                        new
                        {
                            Id = 46,
                            Age = -28,
                            DateOfBirth = new DateTime(1996, 7, 19, 15, 45, 38, 889, DateTimeKind.Local).AddTicks(6192),
                            Departement = "Administration",
                            FullName = "Delbert O'Keefe",
                            PhoneNumber = "(468) 743-1119 x78561"
                        },
                        new
                        {
                            Id = 47,
                            Age = -67,
                            DateOfBirth = new DateTime(1957, 9, 11, 2, 32, 52, 606, DateTimeKind.Local).AddTicks(7307),
                            Departement = "Customer support",
                            FullName = "Emmett Macejkovic",
                            PhoneNumber = "367.679.3809 x90408"
                        },
                        new
                        {
                            Id = 48,
                            Age = -56,
                            DateOfBirth = new DateTime(1968, 7, 1, 7, 34, 38, 394, DateTimeKind.Local).AddTicks(8056),
                            Departement = "Sales",
                            FullName = "Oliver Jacobi",
                            PhoneNumber = "415.901.6987 x0831"
                        },
                        new
                        {
                            Id = 49,
                            Age = -49,
                            DateOfBirth = new DateTime(1975, 4, 27, 1, 49, 27, 432, DateTimeKind.Local).AddTicks(2436),
                            Departement = "Finance",
                            FullName = "Jean Kunze",
                            PhoneNumber = "510-597-1247 x56759"
                        },
                        new
                        {
                            Id = 50,
                            Age = -67,
                            DateOfBirth = new DateTime(1957, 12, 29, 15, 13, 17, 406, DateTimeKind.Local).AddTicks(1211),
                            Departement = "Customer support",
                            FullName = "Willie Williamson",
                            PhoneNumber = "962.457.1157 x6790"
                        },
                        new
                        {
                            Id = 51,
                            Age = -58,
                            DateOfBirth = new DateTime(1966, 12, 22, 0, 17, 57, 954, DateTimeKind.Local).AddTicks(6300),
                            Departement = "Administration",
                            FullName = "Taylor Herman",
                            PhoneNumber = "1-227-203-6596 x387"
                        },
                        new
                        {
                            Id = 52,
                            Age = -21,
                            DateOfBirth = new DateTime(2003, 11, 10, 23, 26, 21, 883, DateTimeKind.Local).AddTicks(9033),
                            Departement = "Information Technology (IT)",
                            FullName = "Ronnie Parisian",
                            PhoneNumber = "249.527.0513 x516"
                        },
                        new
                        {
                            Id = 53,
                            Age = -24,
                            DateOfBirth = new DateTime(2000, 5, 2, 4, 48, 9, 49, DateTimeKind.Local).AddTicks(6762),
                            Departement = "Customer support",
                            FullName = "Miguel Dach",
                            PhoneNumber = "1-255-203-5339 x25115"
                        },
                        new
                        {
                            Id = 54,
                            Age = -29,
                            DateOfBirth = new DateTime(1995, 8, 22, 1, 51, 39, 728, DateTimeKind.Local).AddTicks(9411),
                            Departement = "Business Development",
                            FullName = "Wendell Braun",
                            PhoneNumber = "1-423-205-3281"
                        },
                        new
                        {
                            Id = 55,
                            Age = -67,
                            DateOfBirth = new DateTime(1957, 5, 1, 7, 0, 9, 832, DateTimeKind.Local).AddTicks(6124),
                            Departement = "Training and development",
                            FullName = "Wilfred MacGyver",
                            PhoneNumber = "1-699-512-3830"
                        },
                        new
                        {
                            Id = 56,
                            Age = -48,
                            DateOfBirth = new DateTime(1976, 7, 17, 12, 47, 42, 261, DateTimeKind.Local).AddTicks(7564),
                            Departement = "Information Technology (IT)",
                            FullName = "Tabitha Abbott",
                            PhoneNumber = "(980) 669-6522"
                        },
                        new
                        {
                            Id = 57,
                            Age = -26,
                            DateOfBirth = new DateTime(1998, 1, 8, 2, 13, 8, 774, DateTimeKind.Local).AddTicks(8370),
                            Departement = "Customer support",
                            FullName = "Myra Kuphal",
                            PhoneNumber = "613-570-3520 x656"
                        },
                        new
                        {
                            Id = 58,
                            Age = -62,
                            DateOfBirth = new DateTime(1962, 2, 24, 14, 42, 35, 809, DateTimeKind.Local).AddTicks(3067),
                            Departement = "Information Technology (IT)",
                            FullName = "Kenny Aufderhar",
                            PhoneNumber = "928-570-6009 x29966"
                        },
                        new
                        {
                            Id = 59,
                            Age = -39,
                            DateOfBirth = new DateTime(1985, 7, 7, 13, 36, 1, 809, DateTimeKind.Local).AddTicks(5486),
                            Departement = "Information Technology (IT)",
                            FullName = "Della Quigley",
                            PhoneNumber = "1-281-494-5921 x939"
                        },
                        new
                        {
                            Id = 60,
                            Age = -23,
                            DateOfBirth = new DateTime(2001, 6, 11, 15, 53, 18, 30, DateTimeKind.Local).AddTicks(522),
                            Departement = "Customer support",
                            FullName = "Jeanette Strosin",
                            PhoneNumber = "422-202-4193"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
